name: PowerShell script
author: Pooya Kharamesh
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  eventId:
    description: The event Id of the initiating workflow
    required: true
  telemetryScopeJson:
    description: Telemetry scope generated during the workflow initialization
    required: false
    default: '7b7d'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _eventId: ${{ inputs.eventId }}
        _telemetryScopeJson: ${{ inputs.telemetryScopeJson }}
      run: try { ${{ github.action_path }}/WorkflowPostProcess.ps1 -eventId $ENV:_eventId -telemetryScopeJson $ENV:_telemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
