name: PowerShell script
author: Freddy Kristiansen
inputs:
  project:
    description: Project folder
    required: false
    default: '.'
  parentTelemetryScope:
    description: Specifies the parent telemetry scope for the Telemetry signal
    required: true
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/PipelineCleanup.ps1 -project '${{ inputs.project }}' -parentTelemetryScope '${{ inputs.parentTelemetryScope }}'
      shell: PowerShell
branding:
  icon: terminal
  color: blue