name: PowerShell script
author: Freddy Kristiansen
inputs:
  project:
    description: Project folder
    required: false
    default: '.'
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '{}'
runs:
  using: composite
  steps:
    - run: try { ${{ github.action_path }}/PipelineCleanup.ps1 -project '${{ inputs.project }}' -parentTelemetryScopeJson '${{ inputs.parentTelemetryScopeJson }}' } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
      shell: PowerShell
branding:
  icon: terminal
  color: blue