name: Determine ArtifactUrl to use
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  project:
    description: Project folder
    required: false
    default: '.'
  settingsJson:
    description: Settings from repository in compressed Json format
    required: false
    default: '{"appBuild":0,"appRevision":0}'
  secretsJson:
    description: Secrets from repository in compressed Json format
    required: false
    default: '{"insiderSasToken":""}'
outputs:
  ArtifactUrl:
    description: The ArtifactUrl to use for building this project
    value: ${{ steps.determineArtifactUrl.outputs.ArtifactUrl }}
  ArtifactCacheKey:
    description: The Artifact Cache Key to use for building this project (if using CompilerFolder)
    value: ${{ steps.determineArtifactUrl.outputs.ArtifactCacheKey }}
runs:
  using: composite
  steps:
    - name: Determine ArtifactUrl
      shell: ${{ inputs.shell }}
      id: determineArtifactUrl
      env:
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _project: ${{ inputs.project }}
        _settingsJson: ${{ inputs.settingsJson }}
        _secretsJson: ${{ inputs.secretsJson }}
      run: try { 
          ${{ github.action_path }}/DetermineArtifactUrl.Action.ps1 -parentTelemetryScopeJson $env:_parentTelemetryScopeJson  -project $ENV:_project -settingsJson $ENV:_settingsJson -secretsJson $ENV:_secretsJson
        } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
