name: Build Power Platform Solution
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  solutionFolder:
    description: The Power Platform solution path
    required: false
    default: ''
  outputFolder:
    description: Output folder where the zip file will be placed
    required: false
    default: ''
  outputFileName:
    description: The name of the output zip file
    required: false
    default: '.'
  companyId:
    description: The Business Central company ID
    required: false
    default: ''
  environmentName:
    description: The Business Central environment name
    required: false
    default: ''
  appBuild:
    description: The app build number
    default: ''
    required: false
  appRevision: 
    description: The app revision number
    default: '0'
    required: false


runs:
  using: composite
  steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Update solution settings
      if: ${{ inputs.appBuild != '' }}
      shell: ${{ inputs.shell }}
      env: 
        _solutionFolder: ${{inputs.solutionFolder}}
        _appBuild: ${{inputs.appBuild}}
        _appRevision: ${{inputs.appRevision}}
      run: |
        ${{ github.action_path }}\updateSolutionFile.ps1 -appBuild $ENV:_appBuild -appRevision $ENV:_appRevision -solutionFolder $ENV:_solutionFolder
    
    - name: Update BC connection settings
      if: ${{ inputs.companyId != '' }}
      shell: ${{ inputs.shell }}
      env: 
        _solutionFolder: ${{inputs.solutionFolder}}
        _companyId: ${{inputs.companyId}}
        _environmentName: ${{inputs.environmentName}}        
      run: |
        ${{ github.action_path }}\updateEnvironmentAndCompany.ps1 -companyId $ENV:_companyId -environmentName $ENV:_environmentName -solutionFolder $ENV:_solutionFolder
    
    - name: Test Pack (Not real - just workaround for https://github.com/microsoft/powerplatform-vscode/issues/412)
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-file: forgetMe.zip
        solution-folder: ${{inputs.solutionFolder}}
        process-canvas-apps: true

    - name: Remove test pack
      shell: ${{ inputs.shell }}
      run: |
        Remove-Item -Path forgetMe.zip -Force

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      with:
        solution-file: ${{inputs.outputFolder}}/${{inputs.outputFileName}}.zip
        solution-folder: ${{inputs.solutionFolder}}
        solution-type: "Unmanaged"
        process-canvas-apps: true
     
branding:
  icon: terminal
  color: blue
