name: Download Project Dependencies
author: Microsoft Corporation
description: Downloads the dependencies of an AL-Go project
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  project:
    description: Project for which to download dependencies
    required: true
  buildMode:
    description: Build mode used when building the artifacts
    required: true
  projectDependenciesJson:
    description: A JSON object that matches eash project with its dependency projects
    required: true
  baselineWorkflowRunId:
    description: The ID of the workflow run that was used as baseline for the current build
    required: false
    default: '0'
outputs:
  DownloadedApps:
    description: A JSON-formatted array of paths to .app files of the apps that were downloaded
    value: ${{ steps.DownloadDependencies.outputs.DownloadedApps }}
  DownloadedTestApps:
    description: A JSON-formatted array of paths to .app files of the test apps that were downloaded
    value: ${{ steps.DownloadDependencies.outputs.DownloadedTestApps }}
runs:
  using: composite
  steps:
    - name: Download artifacts from current build
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        path: ${{ github.workspace }}/.dependencies

    - name: Download project dependencies
      shell: ${{ inputs.shell }}
      id: DownloadDependencies
      env:
        _project: ${{ inputs.project }}
        _buildMode: ${{ inputs.buildMode }}
        _projectDependenciesJson: ${{ inputs.projectDependenciesJson }}
        _baseFolder: ${{ github.workspace }}
        _destinationPath: ${{ github.workspace }}/.dependencies
        _gitHubToken: ${{ github.token }}
        _baselineWorkflowRunId: ${{ inputs.baselineWorkflowRunId }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "DownloadProjectDependencies" -Action {
          ${{ github.action_path }}/DownloadProjectDependencies.Action.ps1 -project $ENV:_project -buildMode $ENV:_buildMode -projectDependenciesJson $ENV:_projectDependenciesJson -baselineWorkflowRunId $ENV:_baselineWorkflowRunId -baseFolder $ENV:_baseFolder -destinationPath $ENV:_destinationPath -token $ENV:_gitHubToken
        }
branding:
  icon: terminal
  color: blue
