name: PowerShell script
author: Freddy Kristiansen
inputs:
  settingsJson:
    description: Settings from template repository in compressed Json format
    required: false
    default: '{"keyVaultName": ""}'
  secrets:
    description: Comma separated list of Secrets to get
    required: true
  updateSettingsWithValues:
    description: Specifies if the values of secrets should be updated
    required: false
    default: 'N'
  parentTelemetryScope:
    description: Specifies the parent telemetry scope for the Telemetry signal
    required: false
    default: '' 
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/ReadSecrets.ps1 -settingsJson '${{ inputs.settingsJson }}' -secrets '${{ inputs.secrets }}' -updateSettingsWithValues ('${{ inputs.updateSettingsWithValues }}' -eq 'Y') -parentTelemetryScope '${{ inputs.parentTelemetryScope}}' -telemetryEventId 'DO0078'
      shell: PowerShell
branding:
  icon: terminal
  color: blue