name: PowerShell script
author: Pooya Kharamesh
permissions:
  contents: write
  pull-requests: write
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  tag_name:
    description: Tag name
    required: true
  target_commitish:
    description: Last commit to include in release notes
    required: false
    default: ''
outputs:
  ReleaseBranch:
    description: Name of the release branch
    value: ${{ steps.createreleasenotes.outputs.ReleaseBranch }}
  ReleaseNotes:
    description: Release note generated based on the changes
    value: ${{ steps.createreleasenotes.outputs.ReleaseNotes }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: createreleasenotes
      env:
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _tag_name: ${{ inputs.tag_name }}
        _target_commitish: ${{ inputs.target_commitish }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/CreateReleaseNotes.ps1 -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -tag_name $ENV:_tag_name -target_commitish $ENV:_target_commitish
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
