name: PowerShell script
author: Freddy Kristiansen
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  artifact:
    description: ArtifactUrl to use for the build
    required: false
    default: ''
  project:
    description: Project folder
    required: false
    default: '.'
  buildMode:
    description: Specifies a mode to use for the build steps
    required: false
    default: 'Default'
  installAppsJson:
    description: A JSON-formatted list of apps to install
    required: false
    default: '[]'
  installTestAppsJson:
    description: A JSON-formatted list of test apps to install
    required: false
    default: '[]'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _artifact: ${{ inputs.artifact }}
        _project: ${{ inputs.project }}
        _buildMode: ${{ inputs.buildMode }}
        _installAppsJson: ${{ inputs.installAppsJson }}
        _installTestAppsJson: ${{ inputs.installTestAppsJson }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/RunPipeline.ps1 -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -artifact $ENV:_artifact -project $ENV:_project -buildMode $ENV:_buildMode -installAppsJson $ENV:_installAppsJson -installTestAppsJson $ENV:_installTestAppsJson
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
