name: pre-commit

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: windows-latest
    steps:
    - name: Harden Runner
      if: github.repository_owner == 'microsoft'
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: --all-files
