name: Mark stale issues

on:
  schedule:
  - cron: '44 5 * * 2' # Tuesday, 5:44
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
      with:
        stale-issue-label: 'stale'
        days-before-issue-stale: 180
        days-before-issue-close: 14
        close-issue-message: 'There has been no recent activity on this issue. Please re-open or create a new issue, if needed.'
